### ISSUE TITLE
Missing main.css

### ISSUE THREAD

**Issue by FireAllianceNX** [obber/ghost-minimalist#1]
Hey, awesome theme. When I loaded it, it seems to be missing main.css though. And I can't find it in git either.

**Comment by obber** [comment]
Hey! Sorry for the delayed response.

Go ahead and `cd` into the theme and run `npm run css:build` or `yarn css:build`. That'll generate the main.css file. Hope that helps! (I'll add this to the README)

**Comment by obber** [comment]
I've added a link to the zipped version of the theme in [this commit](https://github.com/obber/ghost-minimalist/commit/83aa7a32027d2a526a8a6e5ff8b71c27b61f4b5d)

You can download it [here](http://kanadachi-themes.objects-us-east-1.dream.io/ghost-minimalist-2.1.2.zip).
